version: '3.8'
services:
  smart-fridge:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./data:/app/data
      - ./uploads:/app/uploads
      - ./static2:/app/static2          # For shopping list data and audio
      - ./ssl_certs:/app/ssl_certs      # Persist SSL certificates
      - ./static:/app/static            # Static web files
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('https://localhost:8000/health', verify=False)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s